namespace :db do
  desc "Add to database MC-1"
  task create_MC1: :environment do
    mc1 = Panzer.create!(name: 'МС-1',
                      country: 'CCCP',
                     country2: 'CCCP',
                        type_: 'lt',
                        level: 1,
                        name2: 'МС-1',
                       to_top: 'base',
                           xp: 100,
                        massa: 5.6,
                   zapas_mass: 900,
               skill_research: 0,
                        price: 0,
                 price_repair: 0,
                 price_valuta: 0,
             processed_fights: 18543,
                 wins_persent: "49.2",
             survived_persent: "26.2",
                      mileage: 521,
                 skill_battle: 144,
                      kredits: 2639,
                        shots: 13,
                     hit_shot: 4,
             hit_shot_persent: 33.0,
              damage_shrapnel: 0,
           hit_shot_effective: 3,
   hit_shot_effective_persent: 0.81,
       score_for_wipped_tracs: 99,
        score_total_help_ally: 26,
             score_for_damage: 3,
       score_for_detect_enemy: 29,
              damage_received: 76,
         detect_enemy_average: 0.73,
        destroy_enemy_average: 0.76,
    score_for_capture_average: 1.25,
          score_for_protected: 0.45,
                cost_recovery: 182,
                profit_battle: 2457,
        profit_battle_premium: 3946)
   end
end
