$(document).on "page:change", ->
  flag = true
  $('#btn_spoiler').click ->
    if flag
      @value = 'Скрыть ↑↑↑↑↑↑↑↑'
      flag = false
    else
      @value = 'Показать ↓↓↓↓↓↓'
      flag = true
# animate hide&unhide check_boxs table in element "#div_spoiler"
    if (@tog = !@tog) then $('#div_spoiler').slideDown(500)
    else $('#div_spoiler').slideUp(500)
  return

# ---
# generated by js2coffee 2.1.0


# $(document).ready(function(){
# 	var flag = true;
#
# 	$("#btn_spoiler").click(function(){
# 		if(flag) { this.value="Скрыть ↑↑↑↑↑↑↑↑"; flag = false; }
# 		else     { this.value="Показать ↓↓↓↓↓↓"; flag = true;  }
#
# // animate hide&unhide check_boxs table in element "#div_spoiler"
# 		return (this.tog = !this.tog) ? $("#div_spoiler").slideDown(500)
# 									  : $("#div_spoiler").slideUp(500);
#     });
# })
